import { containerLayout } from './domain/container-layout.js?v=3.1.4';
import { GEAR_ICONS } from './data/gear-icons.js?v=3.1.4';
import { installDragging } from './ui/drag.js?v=3.1.4';
import { act, loadState, SAVE_KEY, RAID_SECONDS, SEARCH_SECONDS, EXTRACT_SECONDS, CATALOG, QUALITY_NAMES, bagValue, safeValue, freeSlots, carried, estimatedYield, nearestExtraction, travelSeconds, money, clock, rank, contractProgress, choiceAvailable, extractionAvailable, preparation, medLabel, medRemaining } from './domain/expedition.js?v=3.1.4';
import { REGIONS, REGION_BY_ID, CURIOS, CONTRACTS } from './data/expedition.js?v=3.1.4';
import { BACKPACKS, RIGS, EQUIPMENT, MEDICINES } from './data/equipment.js?v=3.1.4';
import { CONNECTIONS, MAP_IMAGE_URL, MAP_IMAGE_SIZE, MAP_VIEW } from './data/map.js?v=3.1.4';
import { firstFit, usedArea } from './domain/inventory.js?v=3.1.4';
import { ENCOUNTERS } from './data/encounters.js?v=3.1.4';
import { CONTAINER_TYPES } from './data/containers.js?v=3.1.4';
import { CONTAINER_ICON_URLS } from './data/container-icons.js?v=3.1.4';
import { LOCAL_ICONS } from './data/local-icons.js?v=3.1.4';
const app=document.querySelector('#app');
installDragging(app,{
  select:(source,id)=>{selection={source,id,rotated:false};clearTimeout(revealTimer);},
  drop:({target,x,y})=>{placeSelection(target,x,y);scheduleReveal();},
  cancel:()=>{selection=null;notify('未放入格子，物品保留在原处。');scheduleReveal();},
});
let storage;
try{storage=window.localStorage;}catch{storage={getItem:()=>null,setItem:()=>{throw Error('Storage unavailable');}};}
let state=loadState(storage),page=state.run?'explore':'camp',modal=null,confirmation=null,selection=null,inventoryTab='bag',shopTab='bag',albumTab='curios';
let revealTimer=null,toastTimer=null,sound=false,audioContext,storageFailed=false;
const esc=t=>String(t??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const shortMoney=n=>n>=100000000?`${(n/100000000).toFixed(2)} 亿`:n>=100000?`${(n/10000).toFixed(1)} 万`:money(n);
const btn=(text,action,attrs='',cls='')=>`<button class="${cls}" data-action="${action}" ${attrs}>${text}</button>`;
const image=(src,alt,cls='')=>`<img class="${cls}" src="${esc(src)}" alt="${esc(alt)}" loading="lazy" decoding="async" draggable="false">`;
const itemArt=item=>(GEAR_ICONS[item.id]||LOCAL_ICONS[item.id])?image(GEAR_ICONS[item.id]||LOCAL_ICONS[item.id],'','item-art'):`<span class="item-symbol" aria-hidden="true">${item.symbol||'◇'}</span>`;
const gearArt=gear=>gear?image(GEAR_ICONS[gear.id],gear.name,'gear-art'):'';
const dial=(seconds,total=120,cls='')=>'<span class="time-dial '+cls+'" style="--angle:'+Math.min(360,360*seconds/total)+'deg" role="img" aria-label="'+seconds+' 秒，占 '+total+' 秒一圈"><span>◷</span></span>';
const costBadge=seconds=>'<span class="time-cost" title="行动耗时：每圈 120 秒">'+dial(seconds)+'<span>'+seconds+' 秒</span></span>';
const inventoryRun=()=>state.run||preparation(state);
const qualityLabel=item=>`<span class="quality-label">${QUALITY_NAMES[item.quality]}</span>`;
function persist(){try{storage.setItem(SAVE_KEY,JSON.stringify(state));storageFailed=false;}catch{storageFailed=true;}}
function notify(text){const e=document.querySelector('#toast');if(!e)return;e.textContent=text;e.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('visible'),3500);}
function chime(q){if(!sound)return;try{audioContext||=new(window.AudioContext||window.webkitAudioContext)();void audioContext.resume();const t=audioContext.currentTime;[0,4,q>=4?12:7].forEach((n,i)=>{const o=audioContext.createOscillator(),g=audioContext.createGain();o.frequency.value=330*2**((q*2+n)/12);g.gain.setValueAtTime(.001,t+i*.07);g.gain.linearRampToValueAtTime(.03,t+i*.07+.02);g.gain.exponentialRampToValueAtTime(.001,t+i*.07+.3);o.connect(g).connect(audioContext.destination);o.start(t+i*.07);o.stop(t+i*.07+.35);});}catch{}}
function dispatch(action){try{const hadRun=Boolean(state.run);const next=action.type==='reveal'?state.run?.loot?.items.find(e=>!e.revealed):null;state=act(state,action);
  if(action.type==='start'){page='explore';modal=null;selection=null;window.scrollTo(0,0);}
  if(hadRun&&!state.run){page='result';modal=null;selection=null;window.scrollTo(0,0);}
  if(selection&&!selectedEntry())selection=null;
  if(action.type==='travel')window.scrollTo(0,0);
  persist();render();scheduleReveal();
  if(next){chime(rank(CATALOG[next.itemId]));notify(`发现${QUALITY_NAMES[CATALOG[next.itemId].quality]}物品：${CATALOG[next.itemId].name}`);}
  return true;
}catch(error){notify(error.message);return false;}}
function scheduleReveal(){clearTimeout(revealTimer);const next=state.run?.loot?.items.find(e=>!e.revealed);if(next&&page==='explore'&&!modal&&!document.hidden)revealTimer=setTimeout(()=>dispatch({type:'reveal'}),500+rank(CATALOG[next.itemId])*170);}
function confirmAction(title,text,action){confirmation={title,text,action};modal='confirm';render();scheduleReveal();}
function guarded(action,cost,extra=''){
  const run=state.run;
  if(action.type==='extract'?run.timeLeft<cost:run.timeLeft<=cost)confirmAction('时间不够完成这次行动',`本次需要 ${clock(cost)}，剩余 ${clock(run.timeLeft)}。继续将因超时撤离失败，只保留保险箱。`,action);
  else if(extra)confirmAction('确认承担这次风险？',extra,action);
  else dispatch(action);
}
function header(){return `<header class="topbar"><a class="brand" href="#" data-action="home"><span class="brand-mark">▧</span><span>箱外之地<small>MINI DELTA FORCE · 零号大坝</small></span></a><div class="top-actions">${btn(sound?'♪':'♫','sound',`aria-label="${sound?'关闭':'开启'}音效" aria-pressed="${sound}"`,'icon-button')}${btn('?','help','aria-label="玩法说明"','icon-button')}</div></header>`;}
function navigation(){return `<nav class="nav" aria-label="主要导航">${btn('⌂ <span>特勤处</span>','home','',page==='camp'?'active':'')}${btn('⌁ <span>战局</span>',state.run?'explore':'prep','',page==='explore'?'active':'')}${btn('▤ <span>收藏手册</span>','album')}${btn('⚒ <span>战前整备</span>','shop')}</nav>`;}
function hud(run,compact=false){const route=nearestExtraction(run);return `<section class="tactical-hud ${compact?'in-modal':''}" aria-label="战局实时状态"><div class="hud-metrics"><div class="${run.timeLeft<=route.seconds+SEARCH_SECONDS?'danger-text':''}"><small>剩余时间 · 30 分钟一圈</small><strong class="time-readout">${dial(run.timeLeft,RAID_SECONDS,'remaining-dial')}${clock(run.timeLeft)}</strong><small>撤离至少 ${clock(route.seconds)}</small></div>${btn(`<small>背包空位</small><strong>${freeSlots(run,'bag')}<em>格</em></strong><small>全身空位 ${freeSlots(run)} 格</small>`,'bag','','hud-bag')}<div><small>预计收益</small><strong title="${money(estimatedYield(run))}">${shortMoney(estimatedYield(run))}</strong><small>保险内 ${shortMoney(safeValue(run))}</small></div></div><div class="hud-health"><span class="${run.hp<=40?'danger-text':''}">✚ ${run.hp}/100 ${run.bleeding?'· 流血中':''}</span><progress value="${run.hp}" max="100" aria-label="生命值"></progress>${btn('用药','medical','','small')}${run.room.threat?'<b class="danger-text">高危搜索</b>':''}</div></section>`;}
function itemCard(entry,source){const item=CATALOG[entry.itemId];if(!entry.revealed)return `<div class="loot-card unrevealed"><div class="scan-line"></div><span class="unknown">?</span><strong>正在搜索</strong><small>揭晓动画不额外扣时间</small></div>`;
  return `<article class="loot-card q-${item.quality} ${entry.taken?'taken':''}" ${source&&!entry.taken?`data-drag-id="${entry.id}" data-drag-source="${source}"`:""}><div class="item-top">${qualityLabel(item)}<span class="size-label">${item.size.join('×')} 格</span></div>${itemArt(item)}<strong>${esc(item.name)}</strong><span class="item-value">${MEDICINES[item.id]?medLabel(entry):money(item.value)}</span>${source?entry.taken?'<span class="packed">✓ 已携带</span>':`${btn('＋ 自动装包','take',`data-id="${entry.id}" data-source="${source}"`,'small')}${btn('选择位置 / 放保险','selectLoot',`data-id="${entry.id}" data-source="${source}"`,'place-link')}`:''}</article>`;
}
function gearSummary(){return ['bag','rig'].map(kind=>{const gear=EQUIPMENT[state.equipment[kind]];return `<span class="equipped-gear">${gearArt(gear)}${kind==='bag'?'背包':'胸挂'}：<b>${gear?gear.name:'未装备'}</b></span>`;}).join('');}
function camp(){return `<section class="camp-hero"><div class="hero-copy"><span class="eyebrow"><i></i> 零号大坝 · 搜索 / 生存 / 撤离</span><h1>箱子要摸，<br><span>也要活着带走。</span></h1><p>听见暗号，先想想要不要信。<br>背包装不下，保险箱还留着一格。</p><div class="hero-buttons">${btn(state.run?'返回战局 ↗':'整备好了，出发 ↗',state.run?'explore':'prep','','primary large')}${btn('购买装备与药品','shop','','quiet')}</div><div class="hero-notes"><span>◷ 30 分钟行动时间</span><span>▧ 按尺寸装包</span></div></div><div class="crate-scene" aria-hidden="true"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><span class="scene-label">ZERO DAM / EXTRACTION</span><div class="rays"></div><div class="hero-crate"><div class="crate-lid"></div><div class="crate-body"><span>?</span><b>LOOT / 003</b></div></div><span class="floating-tag tag-one">✦ 这把能不能出红？</span><span class="floating-tag tag-two">先放保险，心里不慌</span></div></section><section class="camp-stats"><div><small>可用资金</small><strong class="mint">${shortMoney(state.money)}<em>币</em></strong></div><div><small>成功撤离</small><strong>${state.stats.successes}<em>/ ${state.stats.runs} 局</em></strong></div><div><small>收藏发现</small><strong>${Object.keys(state.collection).length}<em>件</em></strong></div><div><small>最高带出</small><strong>${shortMoney(state.stats.best)}<em>币</em></strong></div></section>${state.notice?`<p class="notice">${esc(state.notice)}</p>`:''}<section class="loadout-strip"><div>${gearSummary()}</div><p>本次携药 ${Object.keys(MEDICINES).reduce((n,id)=>n+Math.min(state.loadout[id]||0,state.medicines[id]||0),0)} 件 · 失败掉落穿戴装备；未携带的库存保留</p>${btn('调整出战配置 ↗','prep','','primary')}</section><div class="section-heading"><div><span class="eyebrow">FIELD NOTES</span><h2>搜得多，还得撤得出</h2></div></div><section class="feature-grid"><article class="feature"><span class="feature-icon">▧</span><small>01 / 装包的取舍</small><h3>大红，也得放得下</h3><p>物品尺寸、旋转、分仓与连续空格。保险箱保留，背包胸挂失败掉落。</p></article><article class="feature"><span class="feature-icon peach">◎</span><small>02 / 鼠鼠还是老六</small><h3>暗号有时是陷阱</h3><p>鼠鼠馈赠、背刺、人机巡逻和首领活动。高危硬搜要付出代价。</p></article><article class="feature"><span class="feature-icon lavender">◷</span><small>03 / 留出回家的时间</small><h3>最后一分钟，别贪</h3><p>赶路、用药、搜索都会耗时。去东部或西部撤离点，额外预留 10 秒接应。</p></article></section>${state.lastResult?`<div class="last-trip"><div><small>上一局 · ${state.lastResult.success?'成功撤离':'撤离失败'}</small><strong>带回 ${money(state.lastResult.total)} 币</strong></div>${btn('查看结算 ↗','result','','quiet')}</div>`:''}`;}
function contracts(run){return `<div class="contracts">${run.contracts.map(id=>{const c=CONTRACTS.find(c=>c.id===id),n=Math.min(c.target,contractProgress(run,id));return `<div class="contract ${n===c.target?'complete':''}"><div><span>${n===c.target?'✓':'◇'} ${c.title}</span><b>${n}/${c.target}</b></div><progress value="${n}" max="${c.target}" aria-label="${c.text}"></progress><small>${c.text} · 撤离奖励 ${money(c.reward)}</small></div>`;}).join('')}</div>`;}
function encounterView(run){const e=ENCOUNTERS.find(e=>e.id===run.event.id);return `<section class="event-panel"><div class="event-visual" aria-hidden="true">${e.icon}<span>!</span></div><div class="event-copy"><span class="eyebrow peach-text">大坝遭遇 / ${e.tag}</span><h2>${e.title}</h2><p>${e.text}</p><div class="event-choices">${e.choices.map((c,i)=>btn(`<strong>${c.text} ↗ ${costBadge(c.seconds)}</strong><small>${c.hint}</small>`,'choose',`data-index="${i}" ${choiceAvailable(run,c)?'':'disabled'}`,'choice')).join('')}</div><small class="subtle">可以先用药 · 零钱 ${money(run.coins)} · 血量归零会立即失败</small></div></section>`;}
function lootView(run){
  const loot=run.loot,n=loot.items.filter(e=>!e.revealed).length,left=loot.items.filter(e=>e.revealed&&!e.taken).length;
  const grids=containerLayout(loot.items,CATALOG).map((space,index)=>{
    const cells=Array.from({length:64},(_,i)=>btn('','place','data-target="loot-'+index+'" data-x="'+(i%8)+'" data-y="'+Math.floor(i/8)+'" aria-label="放回容器第'+(Math.floor(i/8)+1)+'行第'+(i%8+1)+'列" style="grid-column:'+(i%8+1)+';grid-row:'+(Math.floor(i/8)+1)+'"','inventory-cell')).join('');
    const items=space.items.filter(e=>!e.taken).map(e=>{
      const item=CATALOG[e.itemId],position='grid-column:'+(e.x+1)+'/span '+e.w+';grid-row:'+(e.y+1)+'/span '+e.h;
      if(!e.revealed)return '<div class="grid-item container-unknown" style="'+position+'" aria-label="尚未揭晓的物品"><span class="scan-line"></span><strong>?</strong></div>';
      const label=item.name+'，'+e.w+'×'+e.h+' 格，'+(MEDICINES[item.id]?medLabel(e):money(item.value)+' 币')+'；点击快速装包，拖拽指定位置';
      return btn(itemArt(item)+'<strong>'+esc(item.name)+'</strong><small>'+e.w+'×'+e.h+'</small>','take','data-source="loot" data-id="'+e.id+'" data-drag-id="'+e.id+'" data-drag-source="loot" aria-label="'+esc(label)+'" title="'+esc(label)+'" style="'+position+'"','grid-item q-'+item.quality);
    }).join('');
    return '<section class="space-panel searched-space"><div class="space-heading"><strong>容器 '+(index+1)+'</strong><small>8×8 · 剩余 '+space.items.filter(e=>!e.taken).length+' 件</small></div><div class="grid-scroll"><div class="inventory-grid searched-grid" data-space="loot-'+index+'" data-width="8" data-height="8" style="--cols:8;--rows:8">'+cells+items+'</div></div></section>';
  }).join('');
  return '<section class="search-panel"><div class="section-heading"><div><span class="eyebrow">'+(n?'SEARCHING / 搜索中':'搜索完成 / 已发现全部物品')+'</span><h2>'+loot.name+'</h2></div><span class="pill">'+(loot.items.length-n)+'/'+loot.items.length+'</span></div>'+grids+'<p class="container-hint">点击物品快速装包；拖拽选择位置 / 放保险。物品按实际尺寸占格，拿走后原位置留空，也能从身上拖回空格；选中身上物品后可点击“放回容器”。</p>'+(loot.guaranteed?'<div class="guarantee">✦ 本箱保底：至少一件'+(loot.guaranteed===4?'金色':'紫色')+'藏品</div>':'')+'<div class="search-actions">'+(n?btn('立即揭晓全部','revealAll','','quiet'):btn('收好，继续探索 →','closeLoot','','continue-search'))+btn('一键装包 · 高价优先','takeAll','data-source="loot" '+(left?'':'disabled'),'primary')+'</div><small class="subtle">快速装包不会动保险箱 · 放不下时可在左侧旋转，再点击目标空格。</small></section>';
}
function roomView(run){const r=REGION_BY_ID[run.locationId];return `<section class="room-panel" style="--region:${r.color}"><div class="room-banner"><span class="region-symbol">${r.icon}</span><div><span class="eyebrow">零号大坝 / ${r.mood}</span><h1>${r.name}</h1><p>${r.subtitle}</p></div></div>${r.extract?`<div class="extract-zone"><strong>${extractionAvailable(run)?'接应已准备好':'本局撤离点不可用'}</strong><p>${extractionAvailable(run)?'前往出生地另一侧的出口，接应只需 10 秒。':'你在同侧出生，请按地图指引前往另一侧撤离。'}</p><p>完成撤离需要 ${EXTRACT_SECONDS} 秒。至少预留 10 秒，接应完成时生命大于 0 即可带走全部物资。</p>${btn('开始撤离 '+costBadge(EXTRACT_SECONDS),'extract',extractionAvailable(run)?'':'disabled','continue-search')}</div>`:`<div class="container-grid">${run.room.boxes.map((box,i)=>btn(`<div class="box-label"><span>容器 0${i+1}</span><b>${box.opened?'已搜索 ✓':box.gilded?'金色保底':'未搜索'}</b></div>${image(CONTAINER_ICON_URLS[box.typeId],'','container-art')}<strong>${CONTAINER_TYPES[box.typeId].name}</strong><small>${box.opened?'不会刷新':`搜索耗时 ${costBadge(SEARCH_SECONDS)}`}</small><span class="box-cta">${box.opened?'已完成':run.room.threat?'⚠ 冒险搜索 ↗':'搜索容器 ↗'}</span>`,'open',`data-id="${box.id}" ${box.opened?'disabled':''}`,'container-card')).join('')}</div>`}</section>`;}
function mapView(run){const links=REGIONS.flatMap(r=>CONNECTIONS[r.id].filter(id=>r.id<id).map(id=>`<line x1="${r.map.x}" y1="${r.map.y}" x2="${REGION_BY_ID[id].map.x}" y2="${REGION_BY_ID[id].map.y}"/>`)).join('');return `<details class="map-details"><summary>零号大坝地图 · 查看当前位置与连通路线</summary><svg viewBox="${MAP_VIEW.x} ${MAP_VIEW.y} ${MAP_VIEW.width} ${MAP_VIEW.height}" role="img" aria-label="零号大坝地图，当前位置${REGION_BY_ID[run.locationId].name}"><image href="${MAP_IMAGE_URL}" width="${MAP_IMAGE_SIZE}" height="${MAP_IMAGE_SIZE}" opacity=".3"/><g stroke="#a8cfb0" stroke-width="5" opacity=".5">${links}</g>${REGIONS.map(r=>`<g><circle cx="${r.map.x}" cy="${r.map.y}" r="${r.id===run.locationId?33:18}" fill="${r.id===run.locationId?'#fff':r.extract?(extractionAvailable(run,r.id)?'#b5efce':'#f18e7d'):r.color}"/><text x="${r.map.x}" y="${r.map.y+65}" text-anchor="middle" fill="#fff" font-size="35">${r.name}${r.extract&&!extractionAvailable(run,r.id)?' ×':''}</text></g>`).join('')}</svg><p>白点是你，绿色是可用出口，红色出口本局不可用；下方路线卡可移动到相邻地点。</p></details>`;}
function routeView(run){const nearest=nearestExtraction(run);return `<section class="route-section"><div class="section-heading"><div><span class="eyebrow">CONNECTED ROUTES</span><h2>选下一条路</h2></div><small class="subtle">往返不会刷新容器</small></div><div class="route-grid">${run.routes.map(id=>{const r=REGION_BY_ID[id];return btn(`<div class="route-top"><span style="color:${r.color}">${r.icon}</span><small>${costBadge(travelSeconds(id))}</small></div><h3>${r.name}</h3><p>${r.extract?(extractionAvailable(run,r.id)?'本局可用 · 接应 10 秒':'同侧出生 · 本局不可撤离'):r.clue}</p><div class="route-bottom"><span>${nearest.path[0]===id?'↗ 推荐撤离方向':r.risk+'风险'}</span><b>移动 ↗</b></div>`,'travel',`data-id="${id}"`,'route-card');}).join('')}</div></section>`;}
function explore(){const run=state.run;if(!run)return camp();const near=nearestExtraction(run),atExit=extractionAvailable(run);return `<div class="expedition-heading"><span class="eyebrow"><i></i> 落地 ${REGION_BY_ID[run.spawnId].name} / ${run.spawnSide==='west'?'西侧':'东侧'} / 已搜 ${run.stats.boxes} 箱</span>${btn('战局手记 ↗','journal','','quiet small')}</div>${run.timeLeft<=near.seconds+SEARCH_SECONDS?`<div class="danger-notice">⚠ 时间吃紧：最近撤离至少需要 ${clock(near.seconds)}，不含遭遇耽搁。别再贪箱。</div>`:''}${run.bleeding?'<div class="danger-notice">流血中：每消耗 10 秒损失 2 点生命。尽快使用绷带；注射器只回血，不止血。</div>':''}${run.room.threat?'<div class="danger-notice">⚠ 高危区域：每次搜索有 65% 概率受到 30–55 点伤害，直到离开这个地点。低血量可能当场失败。</div>':''}${run.event?encounterView(run):`${run.eventResult?`<div class="event-result"><span>${esc(run.eventResult.icon)}</span><div><strong>${esc(run.eventResult.title)}</strong><p>${esc(run.eventResult.text)}</p></div></div>`:''}${run.ground.length?`<section class="ground-panel"><div class="section-heading"><h2>地面物资</h2>${btn('尝试全部装包','takeAll','data-source="ground"','small')}</div><div class="loot-grid">${run.ground.map(e=>itemCard(e,'ground')).join('')}</div></section>`:''}${run.loot?`<div class="search-workspace"><aside class="own-inventory">${inventory()}</aside><div class="container-inventory">${lootView(run)}</div></div>`:`${roomView(run)}<div class="luck-strip"><span>✦ ${run.pity>=3?'下箱必出紫色以上':`保底蓄力 ${run.pity}/3`}</span>${run.luck?`<b>下箱寻宝 +${run.luck}</b>`:''}</div>${mapView(run)}${routeView(run)}`}`}<div class="section-heading compact"><h2>本局委托</h2><small class="subtle">成功撤离后才发奖金</small></div>${contracts(run)}<div class="extraction-bar"><div><small>${atExit?'就在撤离区域':'最近撤离：'+REGION_BY_ID[near.id].name}</small><strong>${clock(near.seconds)}<em>至少需要</em></strong></div>${btn(atExit?'撤离 · 10 秒 ↗':'往撤离点移动 ↗',atExit?'extract':'travel',`${atExit?'':`data-id="${near.path[0]}"`} ${run.event||run.loot?'disabled':''}`,'primary')}<small>${run.event?'先处理遭遇':run.loot?'先收好箱子':'路上遭遇可能额外耗时'}</small></div>`;}
function result(){const r=state.lastResult;if(!r)return camp();const best=[...r.items].sort((a,b)=>CATALOG[b.itemId].value-CATALOG[a.itemId].value).slice(0,4);return `<section class="result-hero ${r.success?'':'failed-result'}"><span class="eyebrow">${r.success?'EXTRACTION COMPLETE':'EXTRACTION FAILED'}</span><div class="result-seal">${r.success?'✓':'×'}</div><h1>${r.success?'这趟，成功带出来了。':'这趟，回特勤处了。'}</h1><p>${esc(r.reason)}<br>${r.success?'背包物资全价兑现，药品返回库存。':'只有保险箱里的物品带回；身上背包、胸挂和其他物资掉落。'}</p><div class="result-total">+ ${money(r.total)}<small>${r.success?'本次带回':'保险箱保留价值'}</small></div><div class="receipt"><div><span>带出藏品</span><b>${money(r.cargo)}</b></div><div><span>带出零钱</span><b>${money(r.coins)}</b></div><div><span>委托奖励</span><b>${money(r.bonus)}</b></div><div><span>返回库存的药品</span><b>${r.returnedMeds} 件</b></div>${r.success?'':`<div><span>物资与装备损失</span><b class="danger-text">${money(r.lostValue)}</b></div>`}</div>${r.lostEquipment.length?`<p class="notice">掉落装备：${r.lostEquipment.map(id=>EQUIPMENT[id].name).join('、')}。仓库中其他未携带的装备不受影响。</p>`:''}<div class="hero-buttons">${btn('回特勤处补给 ↗','home','','primary large')}${btn('购买装备 / 药品','shop','','quiet')}</div></section>${best.length?`<div class="section-heading"><h2>${r.success?'这趟的收获':'保险箱里的最后安慰'}</h2><small>${r.newItems.length} 件新收藏</small></div><div class="loot-grid result-loot">${best.map(e=>itemCard({...e,revealed:true},null)).join('')}</div>`:''}`;}
function selectedEntry(){if(!selection)return null;const run=inventoryRun();return (selection.source==='carry'?carried(run):selection.source==='ground'?run.ground:run.loot?.items)?.find(e=>e.id===selection.id&&!e.taken);}
function selectionSize(e){const size=e.w?[e.w,e.h]:CATALOG[e.itemId].size;return selection?.rotated?[size[1],size[0]]:size;}
function grid(space){return `<section class="space-panel"><div class="space-heading"><strong>${space.label}</strong><small>${space.height}高×${space.width}宽 · 空 ${space.width*space.height-usedArea(space)} 格</small>${space.width*space.height>1?btn('整理','organize',`data-target="${space.key}"`,'small'):''}</div><div class="grid-scroll"><div class="inventory-grid" data-space="${space.key}" data-width="${space.width}" data-height="${space.height}" style="--cols:${space.width};--rows:${space.height}">${Array.from({length:space.width*space.height},(_,i)=>btn('','place',`data-target="${space.key}" data-x="${i%space.width}" data-y="${Math.floor(i/space.width)}" aria-label="放到${space.label}第${Math.floor(i/space.width)+1}行第${i%space.width+1}列" style="grid-column:${i%space.width+1};grid-row:${Math.floor(i/space.width)+1}"`,'inventory-cell')).join('')}${space.items.map(e=>{const item=CATALOG[e.itemId];return btn(`${itemArt(item)}<strong>${esc(item.name)}</strong><small>${MEDICINES[e.itemId]?medRemaining(e)+(MEDICINES[e.itemId].capacity?'点':'次'):e.w+'×'+e.h}</small>`,'selectCarry',`data-id="${e.id}" data-drag-id="${e.id}" data-drag-source="carry" aria-label="${esc(medLabel(e))}，选择${esc(item.name)}，${e.w}乘${e.h}格" style="grid-column:${e.x+1}/span ${e.w};grid-row:${e.y+1}/span ${e.h}"`,`grid-item q-${item.quality} ${selection?.id===e.id?'selected':''}`);}).join('')}</div></div></section>`;}
function inventory(){const run=inventoryRun(),e=selectedEntry(),size=e?selectionSize(e):null;return '<div class="inventory-view"><div class="modal-heading"><span class="eyebrow">'+(state.run?'ON YOUR PERSON / 随身物资':'DEPLOYMENT / 出战摆放')+'</span><h2>装备与物资</h2><p>拖动物品到格子；也可先选物品、旋转，再点空格。背包、胸挂、保险箱和口袋在下面同屏分区显示。</p></div><div class="inventory-selection">'+(e?'<strong>'+esc(CATALOG[e.itemId].name)+' · '+size.join('×')+' 格 · '+medLabel(e)+'</strong><div>'+btn('旋转 ↻','turnSelection','','small')+btn('自动放入所选区域','autoPlace','','primary small')+(state.run?.loot&&selection.source==='carry'?btn('放回容器','returnLoot','data-id="'+e.id+'"','small'):'')+(state.run&&selection.source==='carry'?btn('放到地面','drop','data-id="'+e.id+'"','small'):'')+(state.run&&MEDICINES[e.itemId]&&selection.source==='carry'?btn('使用 '+costBadge(MEDICINES[e.itemId].seconds+(['bag','safeBox'].includes(e.kind)?5:0)),'useMed','data-id="'+e.id+'"','small'):'')+btn('取消','clearSelection','','quiet small')+'</div>':'<span>拖拽以物品左上角落位 · 整理不耗时 · 行动扇形每圈 120 秒</span>')+'</div><nav class="inventory-jumps" aria-label="跳转物资区域">'+[['bag','背包'],['rig','胸挂'],['safeBox','保险箱'],['pockets','口袋']].map(([id,label])=>btn(label+' '+freeSlots(run,id),'inventoryTab','data-tab="'+id+'" aria-pressed="'+(inventoryTab===id)+'"',inventoryTab===id?'active':'')).join('')+'</nav><div class="inventory-scroll">'+[['bag','背包'],['rig','胸挂'],['safeBox','保险箱 3×3'],['pockets','口袋']].map(([kind,label])=>'<section class="inventory-region" data-region="'+kind+'"><div class="region-gear"><h3>'+label+'</h3>'+(['bag','rig'].includes(kind)?gearArt(EQUIPMENT[run.equipment[kind]]):'')+'</div><p class="inventory-rule">'+(kind==='safeBox'?'撤离失败仍保留内部物资。':kind==='rig'?'独立小仓，不能跨仓放置；直接用药。':kind==='pockets'?'6 个独立单格；直接用药。':'需连续空位；从背包取药额外耗时 5 秒。')+'</p><div class="space-list '+(['rig','pockets'].includes(kind)?'compartments':'')+'">'+(run.spaces.filter(sp=>sp.kind===kind).map(grid).join('')||'<p class="notice">未装备。回特勤处购买后可用。</p>')+'</div></section>').join('')+'</div></div>';}
function prep(){const draft=preparation(state);return '<div class="modal-heading"><span class="eyebrow">READY CHECK</span><h2>出战准备</h2><p>这就是落地后物资的位置。拖拽或点击格子调整；部分使用的药品按剩余用量携带。</p></div><div class="loadout-strip">'+gearSummary()+'</div><div class="prep-actions">'+btn('购买 / 选择携带数量','shop','','quiet')+btn('重新自动摆放','resetPrep','','small')+btn('确认装备，随机落地 ↗','start',draft.unplaced.length?'disabled':'','continue-search')+'</div>'+(draft.unplaced.length?'<p class="danger-notice">'+draft.unplaced.length+' 件药品放不下，请减少携带数量或换更大的装备。</p>':'')+inventory();}
function medical(){const run=state.run,meds=carried(run).filter(e=>MEDICINES[e.itemId]);return `<div class="modal-heading"><h2>医疗补给</h2><p>口袋／胸挂直接使用；从背包或保险箱取用额外耗时 5 秒。流血时用药也会经过流血结算，伤势致命前要提前处理。</p></div><div class="bag-list">${meds.map(e=>{const med=MEDICINES[e.itemId],cost=med.seconds+(['bag','safeBox'].includes(e.kind)?5:0);return `<article class="bag-row q-green">${itemArt(CATALOG[e.itemId])}<div><strong>${med.name}</strong><small>${medLabel(e)} · ${med.text} · ${run.spaces.find(s=>s.key===e.spaceKey).label}</small></div>${btn(`使用 ${costBadge(cost)}`,'useMed',`data-id="${e.id}" ${!(med.stopBleed&&run.bleeding)&&(!med.heal||run.hp===100)?'disabled':''}`,'primary small')}</article>`;}).join('')||'<div class="empty"><h3>身上没有可用医疗品</h3><p>医疗容器和蜂医急救点能找到补给。状态不好时优先撤离。</p></div>'}</div>`;}
function shop(){return `<div class="modal-heading"><span class="eyebrow">LOADOUT / 固定游戏售价</span><h2>战前整备</h2><p>资金 <b class="mint">${money(state.money)}</b> · 购买后自动装备；失败掉落本次携带的背包与胸挂。价格取资料快照，非实时交易行。</p></div><div class="loadout-strip">${gearSummary()}${!state.run?btn('查看出战摆放 ↗','prep','','primary'):''}</div><div class="tabs">${[['bag','背包'],['rig','胸挂'],['med','药品 / 携带']].map(([id,label])=>btn(label,'shopTab',`data-tab="${id}"`,shopTab===id?'active':'')).join('')}</div>${shopTab==='med'?`<div class="shop-meds">${Object.entries(MEDICINES).map(([id,m])=>{const n=Math.min(state.loadout[id]||0,state.medicines[id]||0);return `<article class="medicine-shop"><div>${itemArt(CATALOG[id])}<strong>${m.name}</strong><p>${m.text}</p><small>${CATALOG[id].size.join('×')} 格 · 库存 ${state.medicines[id]||0} · 单价 ${money(m.price)}</small></div>${btn('购买 1 件','buyMed',`data-id="${id}" ${state.run||state.money<m.price?'disabled':''}`,'primary small')}<div class="quantity">${btn('−','loadMed',`data-id="${id}" data-count="${n-1}" ${state.run||n===0?'disabled':''}`,'small')}<span>出战携带 ${n}</span>${btn('＋','loadMed',`data-id="${id}" data-count="${n+1}" ${state.run||n>=state.medicines[id]||n>=12?'disabled':''}`,'small')}</div></article>`;}).join('')}</div>`:`<div class="gear-shop">${(shopTab==='bag'?BACKPACKS:RIGS).map(g=>{const size=g.size?g.size[1]+' 格高 × '+g.size[0]+' 格宽':`${g.slots.reduce((n,s)=>n+s[0]*s[1],0)} 格 / ${g.slots.map(s=>s.join('×')).join(' + ')}`,equipped=state.equipment[shopTab]===g.id;return `<article class="gear-card q-${g.quality}">${gearArt(g)}<div><span class="quality-label">${QUALITY_NAMES[g.quality]}</span><h3>${g.name}</h3><p>${size}</p><small>${g.note||'参考市场价快照'} · 库存 ${state.owned[g.id]||0}</small></div><strong>${money(g.price)}<em>币</em></strong><div class="gear-actions">${btn(equipped?'已装备':'装备库存','equip',`data-id="${g.id}" ${state.run||equipped||!state.owned[g.id]?'disabled':''}`,'small')}${btn('购买一件','buyGear',`data-id="${g.id}" ${state.run||state.money<g.price?'disabled':''}`,'primary small')}</div></article>`;}).join('')}</div>`}`;}
function album(){const tab=albumTab;return `<div class="modal-heading"><h2>收藏手册</h2><p>成功带回或保险箱保护的藏品会记录；失败掉落的不算。旧版纪念品仍留在全部收藏里。</p></div><div class="tabs">${[['curios','大坝藏品'],['items','全部收藏'],['events','遭遇档案']].map(([id,label])=>btn(label,'albumTab',`data-tab="${id}"`,tab===id?'active':'')).join('')}</div>${tab==='events'?`<div class="event-book">${ENCOUNTERS.map(e=>`<article class="book-entry ${state.eventBook[e.id]?'':'locked'}"><span>${state.eventBook[e.id]?e.icon:'?'}</span><div><strong>${state.eventBook[e.id]?e.title:'未知遭遇'}</strong><p>${state.eventBook[e.id]?e.text:'探索零号大坝时解锁。'}</p></div></article>`).join('')}</div>`:`<div class="album-grid">${(tab==='curios'?CURIOS:Object.keys(state.collection).map(id=>CATALOG[id]).filter(Boolean).sort((a,b)=>rank(b)-rank(a))).map(item=>`<article class="collection-card q-${item.quality} ${state.collection[item.id]?'':'locked'}">${state.collection[item.id]?itemArt(item):'<span class="item-symbol">?</span>'}${qualityLabel(item)}<strong>${state.collection[item.id]?esc(item.name):'未知大坝藏品'}</strong><p>${state.collection[item.id]?esc(item.story||item.category||'从零号大坝带回的发现。'):'遇到相关事件后，记得装包带走。'}</p><small>${item.size.join('×')} 格 · ${state.collection[item.id]?'已带回 '+state.collection[item.id]+' 件':'未收藏'}</small></article>`).join('')||'<div class="empty">还没有带回的藏品。</div>'}</div>`}`;}
function help(){return `<div class="modal-heading"><h2>搜箱，也要撤离</h2></div><div class="help-copy"><h3>时间是行动预算</h3><p>每局 30 分钟；赶路 90–120 秒，搜索 45 秒，撤离 10 秒。读事件、整理背包和揭晓动画不额外扣时。时间耗尽或生命归零会失败；恰好在最后一秒完成撤离且存活，也算成功。状态栏的撤离时间是最短路估计，不包含沿路遭遇。</p><h3>前往出生地另一侧撤离点</h3><p>在西部撤离点、管道、行政楼东西楼、野外营地或游客中心随机落地，同侧出口不可用。地图使用零号大坝原有地点与连通关系，地点可以返回，但搜过的容器不会刷新。留出接应的 10 秒，不要最后一刻才赶到。</p><h3>格子装包与保险</h3><p>每件物品按原尺寸占格，可旋转和移动。胸挂每个小仓、6 个单格口袋互不连通。保险箱 3×3，失败也保留里面的物品；其他物资、零钱以及穿戴的背包胸挂掉落。</p><h3>医疗与危险</h3><p>强效注射器共 60 点治疗量，每次使用耗时 8 秒；溢出治疗量保留。简易手术包共 2 次，每次止血并恢复 30 生命（简化规则）。绷带止血；流血每累计消耗 10 秒损失 2 生命。药品放在背包或保险箱中，取用额外花 5 秒。高危硬搜有 65% 概率损失 30–55 血，直到离开地点。</p><h3>整备与结算</h3><p>购买的是会掉落的装备，不再是永久升级。库存中的其他装备保留；药品可选择本局携带数量。药品余量在撤离、再出战和刷新后保留。带出的医疗品回药品库存，藏品全价兑现并进图鉴，委托只在成功撤离时付奖。</p><h3>开箱惊喜还在</h3><p>首箱保底紫，连续三箱无紫后下一箱保底紫，第 8 个新搜刮地点的首箱保底金。地点与事件的每点寻宝加成提高紫色以上概率 2 个百分点，最多提高 20 点。</p><p class="notice">本机自动保存。读取页面和整理背包不会偷偷走时间；关闭后可继续。清除浏览器数据会丢失本机存档。</p></div>`;}
function modalContent(){if(modal==='confirm')return `<div class="modal-heading"><h2>${esc(confirmation.title)}</h2><p>${esc(confirmation.text)}</p></div><div class="confirm-actions">${btn('再想想','dismiss','','quiet')}${btn('确认继续','confirm','','primary')}</div>`;if(modal==='prep'&&!state.run)return prep();if(modal==='bag'&&state.run)return inventory();if(modal==='medical'&&state.run)return medical();if(modal==='shop')return shop();if(modal==='album')return album();if(modal==='journal'&&state.run)return `<div class="modal-heading"><h2>战局手记</h2></div><ol class="journal-list">${state.run.log.map(t=>`<li>${esc(t)}</li>`).join('')||'<li>准备出发。</li>'}</ol>`;return help();}
function render(){const inventoryScrolls=[...app.querySelectorAll('.inventory-scroll')].map(e=>e.scrollTop);const active=document.activeElement,key=active?.dataset?.action?{...active.dataset}:null,scroll=document.querySelector('#overlay')?.scrollTop||0;app.innerHTML=`${header()}${navigation()}${state.run?hud(state.run):''}${storageFailed?'<div class="storage-warning" role="alert">浏览器未能保存进度，请保持页面打开，关闭后可能丢失本局。</div>':''}<main>${page==='explore'?explore():page==='result'?result():camp()}</main><footer><span>箱外之地</span>搜箱有惊喜，撤离有取舍。<small>本机自动存档 · v3.1.4</small></footer><div id="toast" class="toast" role="status" aria-live="polite"></div>${modal?`<dialog id="overlay" class="${modal==='confirm'?'compact-modal':''}" aria-label="${modal==='bag'?'背包管理':modal==='medical'?'医疗补给':modal==='shop'?'战前整备':'战局面板'}"><div class="dialog-toolbar">${btn('×','dismiss','aria-label="关闭面板"','modal-close icon-button')}</div>${state.run?hud(state.run,true):''}${modalContent()}</dialog>`:''}`;[...app.querySelectorAll('.inventory-scroll')].forEach((e,i)=>e.scrollTop=inventoryScrolls[i]||0);const dialog=document.querySelector('#overlay');if(dialog){dialog.showModal();dialog.scrollTop=scroll;dialog.addEventListener('cancel',()=>{modal=null;scheduleReveal();});}if(key){const target=[...(dialog||app).querySelectorAll('[data-action]')].find(e=>Object.entries(key).every(([k,v])=>e.dataset[k]===v));target?.focus({preventScroll:true});}}
function placeSelection(target,x,y,auto=false){const e=selectedEntry();if(!e)return notify('先选择一件物品。');const size=selectionSize(e);if(target.startsWith('loot-')){if(selection.source!=='carry')return notify('请从自己的背包、胸挂、口袋或保险箱选择物品放回。');if(dispatch({type:'returnLoot',id:e.id,page:Number(target.slice(5)),placement:{x,y,w:size[0],h:size[1]}})){selection=null;render();notify('已放回容器。');}return;}const space=inventoryRun().spaces.find(s=>s.key===target),p=auto?firstFit(space,size,e.id,false):{x,y,w:size[0],h:size[1]};if(!p)return notify('这个小仓放不下，试试旋转或换个位置。');const action=selection.source==='carry'?{type:state.run?'move':'movePrep',id:e.id,target,placement:p}:{type:'take',id:e.id,source:selection.source,target,placement:p};if(dispatch(action)){selection=null;render();notify('已放好。');}else render();}
app.addEventListener('click',event=>{const target=event.target.closest('[data-action]');if(!target||target.disabled)return;event.preventDefault();const a=target.dataset.action,run=state.run,id=target.dataset.id;
  if(['album','shop','bag','help','journal','medical','prep'].includes(a)){if(['bag','medical','journal'].includes(a)&&!run)return;if(a==='prep'&&run)return;modal=a;selection=null;render();scheduleReveal();return;}
  switch(a){
    case 'dismiss':modal=null;render();scheduleReveal();break;
    case 'confirm':{const next=confirmation.action;modal=null;confirmation=null;dispatch({...next,confirm:true});break;}
    case 'home':page='camp';window.scrollTo(0,0);render();scheduleReveal();break;
    case 'explore':page='explore';window.scrollTo(0,0);render();scheduleReveal();break;
    case 'result':page='result';window.scrollTo(0,0);render();scheduleReveal();break;
    case 'start':dispatch({type:'start'});break;
    case 'sound':sound=!sound;if(sound)chime(2);render();scheduleReveal();break;
    case 'albumTab':albumTab=target.dataset.tab;render();break;
    case 'shopTab':shopTab=target.dataset.tab;render();break;
    case 'inventoryTab':inventoryTab=target.dataset.tab;render();document.querySelector('[data-region="'+inventoryTab+'"]')?.scrollIntoView({behavior:'smooth',block:'nearest'});break;
    case 'buyGear':case 'equip':case 'buyMed':if(dispatch({type:a,id}))notify(a==='equip'?'装备已更换。':'已购买；药品需选择出战携带数量。');break;
    case 'resetPrep':dispatch({type:'resetPrep'});break;
    case 'loadMed':dispatch({type:a,id,count:Number(target.dataset.count)});break;
    case 'open':guarded({type:'open',id},SEARCH_SECONDS,run.room.threat?'本次搜索有 65% 概率损失 30–55 血。生命归零会失败，掉落背包与胸挂；可先用药或离开地点。':'');break;
    case 'choose':{const c=ENCOUNTERS.find(e=>e.id===run.event.id).choices[Number(target.dataset.index)];guarded({type:'choose',index:Number(target.dataset.index)},c.seconds);break;}
    case 'travel':guarded({type:'travel',id},travelSeconds(id),run.ground.length?`地面还有 ${run.ground.length} 件物品，离开就会放弃。确认移动？`:'');break;
    case 'revealAll':clearTimeout(revealTimer);while(state.run?.loot?.items.some(e=>!e.revealed))state=act(state,{type:'reveal'});chime(3);persist();render();break;
    case 'take':if(dispatch({type:'take',id,source:target.dataset.source}))notify('已携带。贵重小件可放入保险箱。');else{selection={source:target.dataset.source,id,rotated:false};render();notify('自动装包放不下：可在左侧旋转，再点空格放置。');}break;
    case 'takeAll':{const before=carried(run).length;if(dispatch({type:'takeAll',source:target.dataset.source}))notify(`装入 ${carried(state.run).length-before} 件；放不下的物品仍留在原处。`);break;}
    case 'selectLoot':selection={source:target.dataset.source,id,rotated:false};modal=run.loot&&page==='explore'?null:'bag';inventoryTab='safeBox';render();scheduleReveal();break;
    case 'selectCarry':selection={source:'carry',id,rotated:false};render();break;
    case 'clearSelection':selection=null;render();break;
    case 'turnSelection':if(selection)selection.rotated=!selection.rotated;render();break;
    case 'place':placeSelection(target.dataset.target,Number(target.dataset.x),Number(target.dataset.y));break;
    case 'autoPlace':{const e=selectedEntry();if(!e)break;const s=inventoryRun().spaces.find(s=>s.kind===inventoryTab&&firstFit(s,selectionSize(e),e.id,false));if(s)placeSelection(s.key,0,0,true);else notify('本区域没有足够的连续空格，可旋转后重试。');break;}
    case 'organize':dispatch({type:run?'organize':'organizePrep',target:target.dataset.target});break;
    case 'returnLoot':if(dispatch({type:'returnLoot',id})){selection=null;render();notify('已放回容器。');}break;
    case 'drop':if(dispatch({type:'drop',id})){selection=null;render();notify('已放到地面，离开地点前仍可捡回。');}break;
    case 'useMed':{const e=carried(run).find(e=>e.id===id);guarded({type:'useMed',id},MEDICINES[e.itemId].seconds+(['bag','safeBox'].includes(e.kind)?5:0));break;}
    case 'closeLoot':if(run.loot.items.some(e=>!e.taken))confirmAction('还有发现没有带上',`将放弃 ${run.loot.items.filter(e=>!e.taken).length} 件物品，确认收好箱子？`,{type:'closeLoot'});else dispatch({type:'closeLoot'});break;
    case 'extract':guarded({type:'extract'},EXTRACT_SECONDS,`撤离耗时 10 秒，当前预计收益 ${money(estimatedYield(run))}。${run.bleeding?'流血仍会造成伤害，请确认状态。':''}${run.ground.length?'未拿的地面物品将被放弃。':''}`);break;
  }
});
document.addEventListener('visibilitychange',()=>{if(document.hidden){clearTimeout(revealTimer);persist();}else scheduleReveal();});window.addEventListener('pagehide',persist);window.addEventListener('pageshow',scheduleReveal);persist();render();scheduleReveal();
